### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by hasan5151** [soarcn/BottomSheet#124]
Fatal Exception: java.lang.ClassCastException: com.cocosw.bottomsheet.SimpleSectionedGridAdapter$Section cannot be cast to android.view.MenuItem
       at com.cocosw.bottomsheet.BottomSheet$4.onItemClick(BottomSheet.java:322)
       at android.widget.AdapterView.performItemClick(AdapterView.java:308)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1510)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3472)
       at android.widget.AbsListView$3.run(AbsListView.java:4835)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5511)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by ngocht143** [comment]
how did you fix it @hasan5151 ?
