### ISSUE TITLE
AbstractMethodError on Android O

### ISSUE THREAD

**Issue by AlexanderThiele** [soarcn/BottomSheet#132]
Hey, i'm using the latest Android O version on Pixel

happens everytime i try to open it

`
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.tnx.apps.coinportfolio, PID: 2885
                                                                          java.lang.AbstractMethodError: abstract method "android.view.MenuItem android.support.v4.internal.view.SupportMenuItem.setAlphabeticShortcut(char, int)"
                                                                              at android.view.MenuInflater$MenuState.setItem(MenuInflater.java:477)
                                                                              at android.view.MenuInflater$MenuState.addItem(MenuInflater.java:541)
                                                                              at android.view.MenuInflater.parseMenu(MenuInflater.java:193)
                                                                              at android.view.MenuInflater.inflate(MenuInflater.java:114)
                                                                              at com.cocosw.bottomsheet.BottomSheet$Builder.sheet(BottomSheet.java:531)
                                                                              at com.tnx.apps.coinportfolio.activity.ManageTransactionsActivity$MyAdapter$1.onClick(ManageTransactionsActivity.java:126)
                                                                              at android.view.View.performClick(View.java:6256)
                                                                              at android.view.View$PerformClick.run(View.java:24697)
                                                                              at android.os.Handler.handleCallback(Handler.java:789)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:164)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**Comment by AlexanderThiele** [comment]
found out that the crash only happens with menu items:
`
new BottomSheet.Builder(MainActivity.this)
.sheet(R.menu.main_long_click) ...
`


Still works with single menu items:

>    new BottomSheet.Builder(MainActivity.this)                   
>   .sheet(R.id.delete, R.drawable.ic_delete_black_24dp, R.string.remove_watchlist)
>                     .sheet(R.id.cancel, R.drawable.ic_close_black_24dp, R.string.cancel)

**Comment by iam1492** [comment]
I also have the same issue but I think we should use google official bottom sheet :).

**Comment by CortoMaltese83** [comment]
Hi, i have the same problem. Can't you release a new version compatible with Android O? I find this library very usefull. By by

**Comment by CortoMaltese83** [comment]
iam1492 you are right, it works. Change compileSdk, library and buildTools to point to android 8. Implement these methods in ActionMenuItem.java and change the return type from null to this. It seems work. 
     
@Override
     public SupportMenuItem setContentDescription(CharSequence contentDescription) {
         return this;
     }

     @Override
     public CharSequence getContentDescription() {
         return null;
     }

     @Override
     public SupportMenuItem setTooltipText(CharSequence tooltipText) {
         return this;
     }

     @Override
     public CharSequence getTooltipText() {
         return null;
     }

     @Override
     public MenuItem setShortcut(char numericChar, char alphaChar, int numericModifiers, int alphaModifiers) {
         return this;
     }

     @Override
     public MenuItem setNumericShortcut(char numericChar, int numericModifiers) {
         return this;
     }

     @Override
     public int getNumericModifiers() {
         return 0;
     }

     @Override
     public MenuItem setAlphabeticShortcut(char alphaChar, int alphaModifiers) {
         return this;
     }

     @Override
     public int getAlphabeticModifiers() {
         return 0;
     }

     @Override
     public MenuItem setIconTintList(ColorStateList tint) {
         return this;
     }

     @Override
     public ColorStateList getIconTintList() {
         return null;
     }

     @Override
     public MenuItem setIconTintMode(PorterDuff.Mode tintMode) {
         return this;
     }

     @Override
     public PorterDuff.Mode getIconTintMode() {
         return null;
     }

**Comment by 8masterofpuppets8** [comment]
I'm having the same issue. Is this planned to be resolved anytime soon?

**Comment by 8masterofpuppets8** [comment]
Btw as a workaround, I did this:

```
PopupMenu p  = new PopupMenu(context, null);
Menu menu = p.getMenu();
MenuInflater inflater = context.getMenuInflater();
inflater.inflate(R.menu.menu_advanced_options, menu);
BottomSheet.Builder builder = new BottomSheet.Builder(context, R.style.BottomSheet_StyleDialog_Dark)
                .title(R.string.create_advanced_options);
for (int i = 0; i < menu.size(); i++) {
    MenuItem item = menu.getItem(i);
    builder = builder.sheet(item.getItemId(), item.getIcon(), item.getTitle());
}
builder = builder.listener(listener);
builder.show();
```

So that I can still use the xml menu but I inflate it programmatically and add the options one by one with the suggested approach above. Seems to work okay on Android O.

**Comment by soarcn** [comment]
Sorry for keep you guys wait for a long time,  updating has been committed and new version 1.3.1 will available soon.
