### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by nickming** [soarcn/BottomSheet#135]
Fatal Exception: java.lang.AbstractMethodError: abstract method "android.view.MenuItem android.support.v4.internal.view.SupportMenuItem.setAlphabeticShortcut(char, int)"
       at android.view.MenuInflater$MenuState.setItem(MenuInflater.java:477)
       at android.view.MenuInflater$MenuState.addItem(MenuInflater.java:541)
       at android.view.MenuInflater.parseMenu(MenuInflater.java:193)
       at android.view.MenuInflater.inflate(MenuInflater.java:114)
       at com.cocosw.bottomsheet.BottomSheet$Builder.sheet(BottomSheet.java:531)
encountered this crash on some devices

**Comment by nickming** [comment]
i have seen that 1.3.1 version had fixed this bug on Android O
