### ISSUE TITLE
BottomSheet crashing on Android 4.1.2 (Galaxy S3)

### ISSUE THREAD

**Issue by taar1** [soarcn/BottomSheet#57]
Testing with a Nexus 5 and Android 5.1 everything works wonderfully. However, when testing it with a Samsung Galaxy S3 mini with Android 4.1.2 BottomSheet keeps crashing when trying to open it.
(we're using BottomSheet version 0.9)

The error is:
06-22 22:33:18.937    2329-2329/ch.post.it.epof.android.client.test E/AndroidRuntime﹕ FATAL EXCEPTION: main
    android.view.InflateException: Binary XML file line #9: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
...
    Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
...
     Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f010038 a=-1}
            at android.content.res.Resources.loadDrawable(Resources.java:1925)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
            at android.view.View.<init>(View.java:3405)
            at android.view.ViewGroup.<init>(ViewGroup.java:432)
            at android.widget.LinearLayout.<init>(LinearLayout.java:176)
            at android.widget.LinearLayout.<init>(LinearLayout.java:172)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.view.View.inflate(View.java:16235)
            at com.cocosw.bottomsheet.BottomSheet.init(BottomSheet.java:265)
            at com.cocosw.bottomsheet.BottomSheet.onCreate(BottomSheet.java:523)
            at android.app.Dialog.dispatchOnCreate(Dialog.java:351)
            at android.app.Dialog.show(Dialog.java:256)
            at com.cocosw.bottomsheet.BottomSheet$Builder.show(BottomSheet.java:830)
            at ch.post.it.epof.android.client.ui.fragments.ItemListFragment.showAddItemDialog(ItemListFragment.java:361)
            at ch.post.it.epof.android.client.ui.fragments.ItemListFragment.AddItemClick(ItemListFragment.java:211)
            at ch.post.it.epof.android.client.ui.fragments.ItemListFragment_$1.onClick(ItemListFragment_.java:94)
            at android.view.View.performClick(View.java:4162)
            at android.view.View$PerformClick.run(View.java:17082)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4867)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
            at dalvik.system.NativeStart.main(Native Method)

Since it works perfectly on the Nexus 5 with the same code I assume it must be an error in BottomSheet. 

Any ideas? Thank you.
...

![device-2015-05-13-153404](https://cloud.githubusercontent.com/assets/2061134/7611899/a9100840-f987-11e4-9a65-b3345758ace6.png)

**Comment by soarcn** [comment]
@taar1 
Please show me your bottomsheet style. According to the error, android can't find drawable for view inflating.  It mostly like something wrong with bs_dialogBackground or bs_dividerColor.

And please try the sample application in your S3, and consider upgrade to at least 1.0

**Comment by taar1** [comment]
Thanks for the answer and sorry for the late reply. 
I could fix the problem. The solution was in fact the lack of the bs_dialogBackground and bs_dividerColor values.
