### ISSUE TITLE
Robolectric tests fail because ClosableSlidingLayout is not public

### ISSUE THREAD

**Issue by objcode** [soarcn/BottomSheet#62]
(PR to follow)

Currently, Robolectric throws an exception because `ClosableSlidingLayout` is not `public`.

    Caused by: java.lang.IllegalAccessException: Class android.view.LayoutInflater can not access a member of class com.cocosw.bottomsheet.ClosableSlidingLayout with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:412)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)

**Comment by soarcn** [comment]
@objcode ,  thanks for you PR, create a testable library is my target but I don't want expose unnecessary class/interface to user.   I don't know how you test bottomsheet by using robolectric ( I would appreciate if you could pull a request with your test case, but one way you can try is put a class to bottomsheet package, which create a proxy to access the class you want.  Have a try and leave a message if you have any questions

**Comment by soarcn** [comment]
And I just saw google start to support @VisibleForTest annotation, not sure it works for robolectric, but worth to try.

**Comment by objcode** [comment]
@soarcn I'll check out `@VisibleForTest` and see if I can get it to work! Definitely agree about polluting the global namespace.
