### ISSUE TITLE
support for subMenus

### ISSUE THREAD

**Issue by marbat87** [soarcn/BottomSheet#85]
Hi,

It would be wonderful having support for submenus,
For example I have a menu xml like the following and the execution terminates with an error:

<pre>
&lt;?xml version="1.0" encoding="utf-8"?>
&lt;menu xmlns:android="http://schemas.android.com/apk/res/android" >
    &lt;item android:id="@+id/add_to_favorites"
        android:title="@string/title_activity_favourites" />
    &lt;item  android:title="@string/title_activity_canti_parola" >
        &lt;menu>
            &lt;item android:id="@+id/add_to_p_iniziale"
                android:title="@string/canto_iniziale" />
            &lt;item android:id="@+id/add_to_p_prima"
                android:title="@string/prima_lettura" />
            ...
        &lt;/menu>
    &lt;/item>
    &lt;item android:title="@string/title_activity_canti_eucarestia" >
        &lt;menu>
            &lt;item android:id="@+id/add_to_e_iniziale"
                android:title="@string/canto_iniziale" />
            &lt;item android:id="@+id/add_to_e_seconda"
                android:title="@string/seconda_lettura" />
           ...
        &lt;/menu>
    &lt;/item>
&lt;/menu>
</pre>

And the error I get is:
<pre>
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.SubMenu.getItem()' on a null object reference
            at android.view.MenuInflater$MenuState.addSubMenuItem(MenuInflater.java:500)
            at android.view.MenuInflater.parseMenu(MenuInflater.java:163)
            at android.view.MenuInflater.inflate(MenuInflater.java:110)
            at com.cocosw.bottomsheet.BottomSheet$Builder.sheet(BottomSheet.java:652)
            at it.cammino.risuscito.RicercaVeloceFragment$2.onLongClick(RicercaVeloceFragment.java:129)
            at android.view.View.performLongClick(View.java:4819)
            at android.view.View$CheckForLongPress.run(View.java:19840)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
</pre>

Thank in advance.

Regards,
Marcello

**Comment by soarcn** [comment]
@marbat87  I try to understand why you need submenu

**Comment by marbat87** [comment]
Because actually I have about 4-5 items in the main menu, each one with a submenu composed by 6-7 elements.
It wouldn't be very nice having a single list with 35 elements.. 
With submenu I can group them and, when user clicks on an element of the main menu, the main menu is replaced with the submenu related to the selected item.

**Comment by soarcn** [comment]
I think you'd better create different menu.xml for different group. I wouldn't support submenu.
